# Dump of table CALENDAR_OBJECTS
# ------------------------------------------------------------

CREATE TABLE CALENDAR_OBJECTS(
 ID             BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
  USERNAME    VARCHAR(255),
  RECORD_DATE       TIMESTAMP,
  REPEAT_TYPE INTEGER,
  CATEGORY VARCHAR(255),
  DESCRIPTION    CLOB(1073741824),
  REMINDER_DAYS INTEGER
) ;
 
 ALTER TABLE CALENDAR_OBJECTS
  ADD PRIMARY KEY
   (ID
   );

# Dump of table CONTACTS
# ------------------------------------------------------------

CREATE TABLE  CONTACTS  (
 ID             BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
   USERNAME  varchar(255) ,
   FIRST_NAME  varchar(100) ,
   MIDDLE_NAME  varchar(100) ,
   LAST_NAME  varchar(100) ,
   TITLE  varchar(50) ,
   SEX  varchar(10) ,
   GSM_NO_PRIMARY  varchar(30) ,
   GSM_NO_ALTERNATE  varchar(30) ,
   EMAIL_PRIMARY  varchar(255) ,
   EMAIL_ALTERNATE  varchar(255) ,
   WEB_PAGE  varchar(255) ,
   PERSONAL_NOTE  CLOB(1073741824),
   SPOUSE_NAME  varchar(255),
   NICK_NAME  varchar(50),
   HOME_ADDRESS  CLOB(1073741824),
   HOME_CITY  varchar(255) ,
   HOME_PROVINCE  varchar(255) ,
   HOME_ZIP  varchar(5) ,
   HOME_COUNTRY  varchar(100) ,
   HOME_PHONE  varchar(30) ,
   HOME_FAKS  varchar(30),
   WORK_COMPANY  varchar(100) ,
   WORK_JOB_TITLE  varchar(100) ,
   WORK_DEPARTMENT  varchar(100) ,
   WORK_OFFICE  varchar(100) ,
   WORK_PROFESSION  varchar(100) ,
   WORK_MANAGER_NAME  varchar(255) ,
   WORK_ASSISTANT_NAME  varchar(255) ,
   WORK_ADDRESS  CLOB(1073741824),
   WORK_CITY  varchar(255) ,
   WORK_PROVINCE  varchar(255),
   WORK_ZIP  varchar(5),
   WORK_COUNTRY  varchar(100) ,
   WORK_PHONE  varchar(30) ,
   WORK_FAKS  varchar(30) ,
   BIRTH_DAY  varchar(2) ,
   ANNIVERSARY_DAY  varchar(2),
   BIRTH_MONTH  varchar(2) ,
   ANNIVERSARY_MONTH  varchar(2) 
) ;
 
 ALTER TABLE CONTACTS
  ADD PRIMARY KEY
   (ID
   );

# Dump of table CONTACT_GROUPS
# ------------------------------------------------------------

CREATE TABLE  CONTACT_GROUPS  (
   ID             BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
   USERNAME  varchar(255) ,
   SHORT_NAME  varchar(100) ,
   DESCRIPTION  varchar(255)
) ;ALTER TABLE CONTACT_GROUPS
  ADD PRIMARY KEY
   (ID
   );

# Dump of table CONTACT_GROUP_OBJECTS
# ------------------------------------------------------------

CREATE TABLE  CONTACT_GROUP_OBJECTS  (
  ID             BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
   USERNAME  varchar(255) ,
   GROUP_ID  bigint,
   CONTACT_ID  bigint
) ;
 ALTER TABLE CONTACT_GROUP_OBJECTS
  ADD PRIMARY KEY
   (ID
   );



# Dump of table FOLDER_DB_OBJECTS
# ------------------------------------------------------------

CREATE TABLE  FOLDER_DB_OBJECTS  (
  ID             BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
   USERNAME  varchar(255) ,
   PARENT_ID  bigint,
   FOLDER_NAME  varchar(100) ,
   FOLDER_TYPE  int
) ;
ALTER TABLE FOLDER_DB_OBJECTS
  ADD PRIMARY KEY
   (ID
   );

# Dump of table MSG_DB_OBJECTS
# ------------------------------------------------------------

CREATE TABLE  MSG_DB_OBJECTS  (
     ID             BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
   USERNAME  varchar(255) ,
   FOLDER_ID  bigint,
   UNIQUE_ID  varchar(100) ,
   UNREAD  int,
   MSG_SIZE  bigint,
   EMAIL  BLOB(30 M)                LOGGED  NOT COMPACT
) ;
ALTER TABLE MSG_DB_OBJECTS
  ADD PRIMARY KEY
   (ID
   );

# Dump of table MSG_RULES
# ------------------------------------------------------------

CREATE TABLE  MSG_RULES  (
    ID             BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
   USERNAME  varchar(255) ,
   PORTION  varchar(100) ,
   RULE_CONDITION  varchar(30) ,
   KEYWORD  varchar(255),
   RULE_ACTION  varchar(30) ,
   DESTINATION  varchar(100) 
) ;
ALTER TABLE MSG_RULES
  ADD PRIMARY KEY
   (ID
   );

# Dump of table NOTES
# ------------------------------------------------------------

CREATE TABLE  NOTES  (
     ID             BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
   USERNAME  varchar(255) ,
   FOLDER_ID  bigint,
   NOTE_CONTENT  CLOB(1073741824),
   POS_LEFT  int,
   POS_TOP  int,
   POS_WIDTH  int,
   POS_HEIGHT  int,
   NOTE_COLOR  varchar(20) ,
   NOTE_BAR_COLOR  varchar(20) ,
   NOTE_BORDER_COLOR  varchar(20) ,
   NOTE_DATE  TIMESTAMP
) ;ALTER TABLE NOTES
  ADD PRIMARY KEY
   (ID
   );


# Dump of table NOTES_FOLDERS
# ------------------------------------------------------------


CREATE TABLE NOTES_FOLDERS
 (ID          BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
  USERNAME    VARCHAR(255),
  FOLDER_NAME     VARCHAR(255)
 );
 
 
ALTER TABLE NOTES_FOLDERS
  ADD PRIMARY KEY
   (ID
   );

# Dump of table PREFERENCES
# ------------------------------------------------------------


CREATE TABLE PREFERENCES
 (ID          BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
  USERNAME    VARCHAR(255),
  PREF_KEY     VARCHAR(255),
  PREF_VALUE  VARCHAR(255)
 );
 
 
ALTER TABLE PREFERENCES
  ADD PRIMARY KEY
   (ID
   );



# Dump of table QUEUE
# ------------------------------------------------------------


CREATE TABLE QUEUE
 (ID             BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
  MSG_FROM       VARCHAR(255),
  MSG_TO         VARCHAR(255),
  MSG_TIME       TIMESTAMP,
  MSG_BODY       BLOB(30 M)                LOGGED  NOT COMPACT,
  MSG_DIRECTION  VARCHAR(3),
  DELIVERED      INTEGER
 );
 
 ALTER TABLE QUEUE
  ADD PRIMARY KEY
   (ID
   );


# Dump of table USER_PREFERENCES
# ------------------------------------------------------------

CREATE TABLE USER_PREFERENCES
 (ID          BIGINT          NOT NULL  GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20, NO CYCLE, NO ORDER),
  USERNAME    VARCHAR(255),
  KEYWORD     VARCHAR(255),
  PREF_VALUE  VARCHAR(255)
 );
 
 
ALTER TABLE USER_PREFERENCES
  ADD PRIMARY KEY
   (ID
   );

